org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.2.0
forge_version_range=[47,)
loader_version_range=[47,)

mapping_channel=official
mapping_version=1.20.1

mod_id=steven_un_mod
mod_name=Steven Un Mod
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=com.stevenunmod
mod_authors=Steven
mod_description=A simple Forge 1.20.1 starter mod for Steven.
